# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1ee27998153cd8eed89406da111a18b8"
application_url = "https://shopify-app-shoelaces.onrender.com"
embedded = true
name = "Shoelaces"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_publications,write_metaobject_definitions,write_metaobjects,write_products,write_publications"

[auth]
redirect_urls = [
  "https://shopify-app-shoelaces.onrender.com/auth/callback",
  "https://shopify-app-shoelaces.onrender.com/auth/shopify/callback",
  "https://shopify-app-shoelaces.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "/api/uploadPDF"
subpath = "shoelaces-upload-pdf"
prefix = "apps"
